GET http://3008/todos/?status=TO%20DO
###

GET http://3008/todos/?priority=HIGH
###

GET http://3008/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://3008/todos/?search_q=Buy
###

GET http://3008/todos/?category=WORK&status=DONE
###

GET http://3008/todos/?category=HOME
###

GET http://3008/todos/?category=LEARNING&priority=HIGH
###






GET http://3008/todos/1/
####


GET http://3008/agenda/?date=2021-12-12
###
POST http://3008/todos/
Content-Type: application/json

{
    "id":10,
    "todo": "Finalize event theme",
    "priority": "LOW",
    "status": "TO DO",
    "category": "HOME",
    "dueDate": "2021-02-22"
}
###

PUT  http://3008/todos/2/
Content-Type: application/json

{
    "status": "DONE"
}
###
PUT  http://3008/todos/2/
Content-Type: application/json

{
    "dueDate": "2021-12-12"
}
###

DELETE http://3008/todos/2/

###
